import { z } from "zod";

export const PROGRESS_REPORT_GENERATION_VERSION = 1;

/** A 4-week block — "current" is the most recent completed block, "prior" is the block immediately before it. */
export const progressReportBlockLabel = z.enum(["current", "prior"]);
export type ProgressReportBlockLabel = z.infer<typeof progressReportBlockLabel>;

export const progressReportDirection = z.enum([
  "improving",
  "declining",
  "stable",
  "insufficient"
]);
export type ProgressReportDirection = z.infer<typeof progressReportDirection>;

// ---------------------------------------------------------------------------
// Facts — deterministic block comparison assembled from the database.
// ---------------------------------------------------------------------------

export const progressReportVolumeBlockSchema = z.object({
  totalMinutes: z.number().int().min(0),
  totalSessions: z.number().int().min(0),
  keySessionsCompleted: z.number().int().min(0),
  keySessionsPlanned: z.number().int().min(0),
  completionPct: z.number().int().min(0).max(999),
  perSport: z.object({
    run: z.number().int().min(0),
    bike: z.number().int().min(0),
    swim: z.number().int().min(0),
    strength: z.number().int().min(0),
    other: z.number().int().min(0)
  })
});

export type ProgressReportVolumeBlock = z.infer<typeof progressReportVolumeBlockSchema>;

export const progressReportFitnessPointSchema = z.object({
  sport: z.enum(["run", "bike", "swim", "total"]),
  currentCtlStart: z.number(),
  currentCtlEnd: z.number(),
  currentCtlDelta: z.number(),
  priorCtlEnd: z.number().nullable(),
  deltaVsPrior: z.number().nullable(),
  rampRate: z.number().nullable(),
  direction: progressReportDirection
});

export type ProgressReportFitnessPoint = z.infer<typeof progressReportFitnessPointSchema>;

export const progressReportPaceAtHrSchema = z.object({
  sport: z.enum(["run", "bike", "swim"]),
  current: z.object({
    avgHr: z.number().nullable(),
    avgPaceSecPerKm: z.number().nullable(),
    avgPacePer100mSec: z.number().nullable(),
    avgPower: z.number().nullable(),
    sessionCount: z.number().int().min(0)
  }),
  prior: z.object({
    avgHr: z.number().nullable(),
    avgPaceSecPerKm: z.number().nullable(),
    avgPacePer100mSec: z.number().nullable(),
    avgPower: z.number().nullable(),
    sessionCount: z.number().int().min(0)
  }),
  direction: progressReportDirection,
  summary: z.string().min(1).max(240)
});

export type ProgressReportPaceAtHr = z.infer<typeof progressReportPaceAtHrSchema>;

export const progressReportDurabilityBlockSchema = z.object({
  enduranceSessions: z.number().int().min(0),
  decouplingSamples: z.number().int().min(0),
  avgDecouplingPct: z.number().nullable(),
  poorDurabilityCount: z.number().int().min(0)
});

export const progressReportDurabilitySchema = z.object({
  current: progressReportDurabilityBlockSchema,
  prior: progressReportDurabilityBlockSchema,
  direction: progressReportDirection,
  summary: z.string().min(1).max(240)
});

export type ProgressReportDurability = z.infer<typeof progressReportDurabilitySchema>;

export const progressReportPeakSchema = z.object({
  sport: z.enum(["run", "bike", "swim"]),
  label: z.string().min(1).max(60),
  current: z.object({
    value: z.number(),
    formatted: z.string().min(1).max(40),
    activityId: z.string().nullable(),
    activityDate: z.string().nullable()
  }),
  prior: z.object({
    value: z.number().nullable(),
    formatted: z.string().nullable()
  }),
  delta: z.number().nullable(),
  deltaLabel: z.string().nullable()
});

export type ProgressReportPeak = z.infer<typeof progressReportPeakSchema>;

export const progressReportFactsSchema = z.object({
  blockStart: z.string().date(),
  blockEnd: z.string().date(),
  priorBlockStart: z.string().date(),
  priorBlockEnd: z.string().date(),
  blockLabel: z.string().min(1).max(120),
  blockRange: z.string().min(1).max(80),
  priorBlockRange: z.string().min(1).max(80),
  volume: z.object({
    current: progressReportVolumeBlockSchema,
    prior: progressReportVolumeBlockSchema,
    deltaMinutes: z.number().int(),
    deltaSessions: z.number().int()
  }),
  fitnessTrajectory: z.array(progressReportFitnessPointSchema),
  paceAtHrByDiscipline: z.array(progressReportPaceAtHrSchema),
  durability: progressReportDurabilitySchema,
  peakPerformances: z.array(progressReportPeakSchema).max(6),
  factualBullets: z.array(z.string().min(1).max(200)).min(2).max(6),
  confidenceNote: z.string().min(1).max(240).nullable(),
  narrativeSource: z.enum(["ai", "fallback", "legacy_unknown"]).default("legacy_unknown")
});

export type ProgressReportFacts = z.infer<typeof progressReportFactsSchema>;

// ---------------------------------------------------------------------------
// Narrative — athlete-facing copy generated by the AI pass.
// ---------------------------------------------------------------------------

export const progressReportDisciplineVerdictSchema = z.object({
  sport: z.enum(["run", "bike", "swim"]),
  verdict: z.string().min(1).max(260)
});

export type ProgressReportDisciplineVerdict = z.infer<
  typeof progressReportDisciplineVerdictSchema
>;

export const progressReportNarrativeSchema = z.object({
  coachHeadline: z.string().min(1).max(120),
  executiveSummary: z.string().min(1).max(460),
  fitnessReport: z.string().min(1).max(340),
  durabilityReport: z.string().min(1).max(340),
  peakPerformancesReport: z.string().min(1).max(340),
  disciplineVerdicts: z
    .array(progressReportDisciplineVerdictSchema)
    .min(1)
    .max(3),
  /**
   * Required cross-block finding an athlete would not see by skimming weekly
   * debriefs — e.g. "Run pace-at-HR improved 6s/km while bike power stalled,
   * yet CTL climbed in both — recovery is concentrating adaptation on running."
   */
  nonObviousInsight: z.string().min(1).max(380),
  /**
   * Optional one-sentence teach moment explaining *why* a metric the block
   * exposes matters (aerobic decoupling, CTL ramp, pace-at-HR, durability
   * fade, etc.). Null when no mechanism is worth teaching this block.
   */
  teach: z.string().min(1).max(220).nullable(),
  carryForward: z.array(z.string().min(1).max(280)).min(2).max(2)
});

export type ProgressReportNarrative = z.infer<typeof progressReportNarrativeSchema>;

// ---------------------------------------------------------------------------
// Artifact — what lands in the DB as a single row.
// ---------------------------------------------------------------------------

export const progressReportArtifactSchema = z.object({
  blockStart: z.string().date(),
  blockEnd: z.string().date(),
  status: z.enum(["ready", "stale", "failed"]),
  sourceUpdatedAt: z.string().datetime(),
  generatedAt: z.string().datetime(),
  generationVersion: z.number().int().positive(),
  facts: progressReportFactsSchema,
  narrative: progressReportNarrativeSchema,
  feedback: z.object({
    helpful: z.boolean().nullable(),
    accurate: z.boolean().nullable(),
    note: z.string().nullable(),
    updatedAt: z.string().datetime().nullable()
  })
});

export type ProgressReportArtifact = z.infer<typeof progressReportArtifactSchema>;

export type ProgressReportRecord = {
  block_start: string;
  block_end: string;
  status: "ready" | "stale" | "failed";
  source_updated_at: string;
  generated_at: string;
  generation_version: number;
  facts: unknown;
  narrative: unknown;
  helpful: boolean | null;
  accurate: boolean | null;
  feedback_note: string | null;
  feedback_updated_at: string | null;
};

export const progressReportFeedbackInputSchema = z.object({
  blockStart: z.string().date(),
  helpful: z.boolean().nullable(),
  accurate: z.boolean().nullable(),
  note: z.string().trim().max(400).nullable().optional()
});

export type ProgressReportFeedbackInput = z.infer<
  typeof progressReportFeedbackInputSchema
>;
