// Plan / sessions seed rows for the preview database. Pulled out of
// data-scenarios.ts so the umbrella file stays scannable.

import {
  PREVIEW_BLOCK_BASE_ID,
  PREVIEW_BLOCK_BUILD_ID,
  PREVIEW_PLAN_ID,
  PREVIEW_RACE_SESSION_ID,
  PREVIEW_USER_ID,
  PREVIEW_WEEK_FIVE_ID,
  PREVIEW_WEEK_FOUR_ID,
  PREVIEW_WEEK_ONE_ID,
  PREVIEW_WEEK_THREE_ID,
  PREVIEW_WEEK_TWO_ID
} from "./data-types";
import {
  RACE_TOTAL_DURATION_SEC,
  previewDateOffset,
  previewMonday,
  previewPriorRaceMonday
} from "./data-factories";

export function buildPlanRows() {
  return {
    profiles: [
      {
        id: PREVIEW_USER_ID,
        display_name: "Preview Athlete",
        avatar_url: null,
        active_plan_id: PREVIEW_PLAN_ID,
        race_date: "2026-06-21",
        race_name: "Galway 70.3"
      }
    ],
    training_plans: [
      {
        id: PREVIEW_PLAN_ID,
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        name: "70.3 Build Block",
        start_date: "2026-03-09",
        duration_weeks: 12,
        updated_at: "2026-03-15T08:00:00.000Z"
      }
    ],
    training_blocks: [
      {
        id: PREVIEW_BLOCK_BASE_ID,
        user_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        season_id: null,
        name: "Base 1",
        block_type: "Base",
        start_date: "2026-03-09",
        end_date: "2026-03-29",
        target_race_id: null,
        emphasis: {},
        notes: "Aerobic base with controlled intensity touches.",
        sort_order: 0
      },
      {
        id: PREVIEW_BLOCK_BUILD_ID,
        user_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        season_id: null,
        name: "Build 1",
        block_type: "Build",
        start_date: "2026-03-30",
        end_date: "2026-06-21",
        target_race_id: null,
        emphasis: {},
        notes: "Race-pace work anchored by two key sessions per week.",
        sort_order: 1
      }
    ],
    training_weeks: [
      {
        id: PREVIEW_WEEK_ONE_ID,
        plan_id: PREVIEW_PLAN_ID,
        block_id: PREVIEW_BLOCK_BASE_ID,
        week_index: 1,
        week_start_date: "2026-03-09",
        focus: "Build",
        notes: "Settle into the build and keep easy days honest.",
        target_minutes: 510,
        target_tss: 430
      },
      {
        id: PREVIEW_WEEK_TWO_ID,
        plan_id: PREVIEW_PLAN_ID,
        block_id: PREVIEW_BLOCK_BASE_ID,
        week_index: 2,
        week_start_date: "2026-03-16",
        focus: "Build",
        notes: "Carry bike quality, keep long run smooth.",
        target_minutes: 560,
        target_tss: 470
      },
      {
        id: PREVIEW_WEEK_THREE_ID,
        plan_id: PREVIEW_PLAN_ID,
        block_id: PREVIEW_BLOCK_BASE_ID,
        week_index: 3,
        week_start_date: "2026-03-23",
        focus: "Recovery",
        notes: "Reduce volume and absorb work.",
        target_minutes: 360,
        target_tss: 280
      },
      {
        id: PREVIEW_WEEK_FOUR_ID,
        plan_id: PREVIEW_PLAN_ID,
        block_id: PREVIEW_BLOCK_BUILD_ID,
        week_index: 4,
        week_start_date: "2026-03-30",
        focus: "Build",
        notes: "Ramp back up after recovery. Two key sessions anchor the week.",
        target_minutes: 540,
        target_tss: 450
      },
      {
        id: PREVIEW_WEEK_FIVE_ID,
        plan_id: PREVIEW_PLAN_ID,
        block_id: PREVIEW_BLOCK_BUILD_ID,
        week_index: 5,
        week_start_date: previewMonday(),
        focus: "Build",
        notes: "Continue build phase with balanced discipline work.",
        target_minutes: 520,
        target_tss: 440
      }
    ],
    sessions: [
      {
        id: "77777777-7777-4777-8777-777777777771",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-09",
        sport: "swim",
        discipline: "swim",
        type: "CSS Intervals",
        session_name: "CSS Intervals",
        target: "12 x 100m @ CSS with 20s rest",
        duration_minutes: 50,
        intent_category: "threshold",
        session_role: "key",
        status: "completed",
        day_order: 1,
        notes: "Strong control through the final block.",
        created_at: "2026-03-08T18:00:00.000Z",
        is_key: true,
        execution_result: {
          status: "matched_intent",
          executionScore: 91,
          executionScoreBand: "On target",
          executionScoreSummary: "Pacing stayed tight and the intended threshold stimulus landed.",
          whyItMatters: "This supports swim economy without adding unnecessary fatigue.",
          recommendedNextAction: "Keep the same send-off next week and hold stroke length through the final reps."
        }
      },
      {
        id: "77777777-7777-4777-8777-777777777772",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-10",
        sport: "bike",
        discipline: "bike",
        type: "FTP Build",
        session_name: "FTP Build",
        target: "3 x 12 min @ 92-95% FTP",
        duration_minutes: 75,
        intent_category: "threshold",
        session_role: "key",
        status: "completed",
        day_order: 1,
        notes: null,
        created_at: "2026-03-08T18:01:00.000Z",
        is_key: true,
        execution_result: {
          status: "partial_intent",
          executionScore: 74,
          executionScoreBand: "Partial match",
          executionScoreSummary: "The first two reps landed, but power faded late.",
          whyItMatters: "Late fade reduces the quality of the session's sustained-threshold signal.",
          recommendedNextAction: "NEXT threshold set: 3×12 min @ 245–255W, 6 min easy between. If average interval power holds ≥248W through all three reps, extend the final rep to 14 min.",
          componentScores: {
            intentMatch: { score: 70, weight: 0.4, detail: "HR missing — cannot verify cardiovascular load against threshold target." },
            pacingExecution: { score: 65, weight: 0.25, detail: "Power faded ~6% on the final rep; variability index 1.08." },
            completion: { score: 85, weight: 0.2, detail: "All three reps completed; total duration matched plan." },
            recoveryCompliance: { score: 80, weight: 0.15, detail: "TSS within the weekly envelope; next-day session still easy." },
            composite: 74,
            dataCompletenessPct: 0.55,
            missingCriticalData: ["Heart rate"]
          }
        }
      },
      {
        id: "77777777-7777-4777-8777-777777777773",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-11",
        sport: "run",
        discipline: "run",
        type: "Easy Run",
        session_name: "Easy Run",
        target: "45 min easy aerobic",
        duration_minutes: 45,
        intent_category: "easy",
        session_role: "supporting",
        status: "completed",
        day_order: 1,
        notes: null,
        created_at: "2026-03-08T18:02:00.000Z",
        is_key: false,
        execution_result: {
          status: "matched_intent",
          executionScore: 88,
          executionScoreBand: "On target",
          executionScoreSummary: "A relaxed aerobic run that stayed well controlled.",
          whyItMatters: "It preserved recovery between the heavier bike and brick work.",
          recommendedNextAction: "Keep cadence light and avoid drifting into steady-state effort."
        }
      },
      {
        id: "77777777-7777-4777-8777-777777777774",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-12",
        sport: "bike",
        discipline: "bike",
        type: "Aerobic Ride",
        session_name: "Aerobic Ride",
        target: "60 min easy spin",
        duration_minutes: 60,
        intent_category: "recovery",
        session_role: "recovery",
        status: "skipped",
        day_order: 1,
        notes: "[skipped 2026-03-12] Travel day compression.",
        created_at: "2026-03-08T18:03:00.000Z",
        is_key: false,
        execution_result: {
          status: "missed_intent",
          executionScore: 42,
          executionScoreBand: "Missed intent",
          executionScoreSummary: "The recovery spin was skipped, so the week lost an easy flush session.",
          whyItMatters: "Missing low-cost recovery work can make the weekend feel heavier than it should.",
          recommendedNextAction: "Do not cram this back in. Protect the weekend key sessions instead."
        }
      },
      {
        id: "77777777-7777-4777-8777-777777777775",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-13",
        sport: "run",
        discipline: "run",
        type: "Brick Run",
        session_name: "Brick Run",
        target: "35 min steady off the bike",
        duration_minutes: 35,
        intent_category: "threshold",
        session_role: "key",
        status: "skipped",
        day_order: 1,
        notes: null,
        created_at: "2026-03-08T18:04:00.000Z",
        is_key: true,
        execution_result: null
      },
      {
        id: "77777777-7777-4777-8777-777777777776",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-14",
        sport: "bike",
        discipline: "bike",
        type: "Race Prep Brick",
        session_name: "Race Prep Brick",
        target: "2h bike + 20 min run",
        duration_minutes: 140,
        intent_category: "long",
        session_role: "key",
        status: "skipped",
        day_order: 1,
        notes: "Fuel every 20 min and stay capped on climbs.",
        created_at: "2026-03-08T18:05:00.000Z",
        is_key: true,
        execution_result: null
      },
      {
        id: "77777777-7777-4777-8777-777777777777",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_ONE_ID,
        date: "2026-03-15",
        sport: "run",
        discipline: "run",
        type: "Long Run",
        session_name: "Long Run",
        target: "95 min aerobic with last 15 steady",
        duration_minutes: 95,
        intent_category: "long",
        session_role: "key",
        status: "completed",
        day_order: 1,
        notes: "Legs felt heavy from the start. HR crept up despite easy pace. Cut the last 3km.",
        created_at: "2026-03-08T18:06:00.000Z",
        is_key: true,
        execution_result: {
          status: "partial_intent",
          intentMatchStatus: "partial_intent",
          executionScore: 68,
          executionScoreBand: "Partial match",
          executionScoreSummary: "HR elevated 8bpm above easy ceiling. Significant pace drift in the final third. Session cut short by 7 minutes.",
          whyItMatters: "Elevated HR and late fade suggest incomplete recovery from midweek sessions. The aerobic stimulus was partially delivered but at higher physiological cost than intended.",
          recommendedNextAction: "Reduce Tuesday's threshold intensity to protect recovery before the next key bike session."
        }
      },
      {
        id: "77777777-7777-4777-8777-777777777778",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_TWO_ID,
        date: "2026-03-16",
        sport: "swim",
        discipline: "swim",
        type: "Pull Endurance",
        session_name: "Pull Endurance",
        target: "3 x 600 pull aerobic",
        duration_minutes: 55,
        intent_category: "easy",
        session_role: "supporting",
        status: "planned",
        day_order: 1,
        notes: null,
        created_at: "2026-03-08T18:07:00.000Z",
        is_key: false,
        execution_result: null
      },
      // ── Week 4 sessions (current week: 2026-03-30 → 2026-04-05) ──
      {
        id: "77777777-7777-4777-8777-77777777778a",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_FOUR_ID,
        date: "2026-03-30",
        sport: "swim",
        discipline: "swim",
        type: "CSS Intervals",
        session_name: "CSS Intervals",
        target: "10 x 100m @ CSS with 15s rest",
        duration_minutes: 50,
        intent_category: "threshold",
        session_role: "key",
        status: "completed",
        day_order: 1,
        notes: "Smooth turnover through the final set.",
        created_at: "2026-03-29T18:00:00.000Z",
        is_key: true,
        execution_result: {
          status: "matched_intent",
          executionScore: 89,
          executionScoreBand: "On target",
          executionScoreSummary: "CSS pace held consistently with controlled rest intervals.",
          whyItMatters: "Threshold swim work builds lactate clearance for race-day pacing.",
          recommendedNextAction: "Maintain the same send-off; consider adding 2 reps next week."
        }
      },
      {
        id: "77777777-7777-4777-8777-77777777778b",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_FOUR_ID,
        date: "2026-03-31",
        sport: "bike",
        discipline: "bike",
        type: "FTP Intervals",
        session_name: "FTP Intervals",
        target: "3 x 12 min @ 92-95% FTP",
        duration_minutes: 75,
        intent_category: "threshold",
        session_role: "key",
        status: "completed",
        day_order: 1,
        notes: null,
        created_at: "2026-03-29T18:01:00.000Z",
        is_key: true,
        execution_result: {
          status: "matched_intent",
          executionScore: 85,
          executionScoreBand: "On target",
          executionScoreSummary: "Power held steady across all three intervals. Cadence consistent at 88rpm.",
          whyItMatters: "Clean FTP work confirms threshold capacity is tracking well for race build.",
          recommendedNextAction: "NEXT sweet-spot set: 3×12 min @ 250–260W, 6 min easy between. If average interval power holds ≥255W and cadence stays 88rpm, extend the third rep to 15 min."
        }
      },
      {
        id: "77777777-7777-4777-8777-77777777778c",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_FOUR_ID,
        date: "2026-04-01",
        sport: "run",
        discipline: "run",
        type: "Easy Run",
        session_name: "Easy Run",
        target: "40 min easy aerobic",
        duration_minutes: 40,
        intent_category: "easy",
        session_role: "recovery",
        status: "completed",
        day_order: 1,
        notes: null,
        created_at: "2026-03-29T18:02:00.000Z",
        is_key: false,
        execution_result: {
          status: "matched_intent",
          executionScore: 92,
          executionScoreBand: "On target",
          executionScoreSummary: "A controlled easy run. HR stayed well below the aerobic ceiling.",
          whyItMatters: "Flush run between key sessions supports recovery.",
          recommendedNextAction: "Keep these honest — avoid steady-state drift."
        }
      },
      {
        id: "77777777-7777-4777-8777-77777777778d",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_FOUR_ID,
        date: "2026-04-02",
        sport: "strength",
        discipline: "strength",
        type: "Core & Mobility",
        session_name: "Core & Mobility",
        target: "Core stability + hip mobility circuit",
        duration_minutes: 30,
        intent_category: "recovery",
        session_role: "supporting",
        status: "planned",
        day_order: 1,
        notes: null,
        created_at: "2026-03-29T18:03:00.000Z",
        is_key: false,
        execution_result: null
      },
      {
        id: "77777777-7777-4777-8777-77777777778e",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_FOUR_ID,
        date: "2026-04-04",
        sport: "run",
        discipline: "run",
        type: "Tempo Run",
        session_name: "Tempo Run",
        target: "45 min with 3 x 8 min @ threshold",
        duration_minutes: 45,
        intent_category: "threshold",
        session_role: "key",
        status: "planned",
        day_order: 1,
        notes: "Focus on cadence and relaxed shoulders.",
        created_at: "2026-03-29T18:04:00.000Z",
        is_key: true,
        execution_result: null
      },
      {
        id: "77777777-7777-4777-8777-77777777778f",
        user_id: PREVIEW_USER_ID,
        athlete_id: PREVIEW_USER_ID,
        plan_id: PREVIEW_PLAN_ID,
        week_id: PREVIEW_WEEK_FOUR_ID,
        date: "2026-04-05",
        sport: "bike",
        discipline: "bike",
        type: "Long Ride",
        session_name: "Long Ride",
        target: "2h30 aerobic with rolling hills",
        duration_minutes: 150,
        intent_category: "long",
        session_role: "key",
        status: "planned",
        day_order: 1,
        notes: "Fuel every 20 min. Cap power on climbs.",
        created_at: "2026-03-29T18:05:00.000Z",
        is_key: true,
        execution_result: null
      },
      // ── Week 5 sessions (current week — dynamically dated) ──
      ...(() => {
        const mon = previewMonday();
        return [
          {
            id: "77777777-7777-4777-8777-777777777790",
            user_id: PREVIEW_USER_ID,
            athlete_id: PREVIEW_USER_ID,
            plan_id: PREVIEW_PLAN_ID,
            week_id: PREVIEW_WEEK_FIVE_ID,
            date: previewDateOffset(mon, 0),
            sport: "swim",
            discipline: "swim",
            type: "Endurance Swim",
            session_name: "Endurance Swim",
            target: "2000m continuous aerobic",
            duration_minutes: 45,
            intent_category: "easy",
            session_role: "supporting",
            status: "completed",
            day_order: 1,
            notes: null,
            created_at: new Date().toISOString(),
            is_key: false,
            execution_result: { status: "matched_intent", executionScore: 88, executionScoreBand: "On target", executionScoreSummary: "Solid aerobic swim.", whyItMatters: "Builds aerobic base.", recommendedNextAction: "Maintain." }
          },
          {
            id: "77777777-7777-4777-8777-777777777791",
            user_id: PREVIEW_USER_ID,
            athlete_id: PREVIEW_USER_ID,
            plan_id: PREVIEW_PLAN_ID,
            week_id: PREVIEW_WEEK_FIVE_ID,
            date: previewDateOffset(mon, 1),
            sport: "bike",
            discipline: "bike",
            type: "Sweet Spot Intervals",
            session_name: "Sweet Spot Intervals",
            target: "3 x 15 min @ 88-93% FTP",
            duration_minutes: 75,
            intent_category: "threshold",
            session_role: "key",
            status: "completed",
            day_order: 1,
            notes: null,
            created_at: new Date().toISOString(),
            is_key: true,
            execution_result: { status: "matched_intent", executionScore: 82, executionScoreBand: "On target", executionScoreSummary: "Intervals clean.", whyItMatters: "Sweet spot builds FTP.", recommendedNextAction: "Hold same targets." }
          },
          {
            id: "77777777-7777-4777-8777-777777777792",
            user_id: PREVIEW_USER_ID,
            athlete_id: PREVIEW_USER_ID,
            plan_id: PREVIEW_PLAN_ID,
            week_id: PREVIEW_WEEK_FIVE_ID,
            date: previewDateOffset(mon, 2),
            sport: "run",
            discipline: "run",
            type: "Easy Run",
            session_name: "Easy Run",
            target: "35 min easy aerobic",
            duration_minutes: 35,
            intent_category: "easy",
            session_role: "recovery",
            status: "completed",
            day_order: 1,
            notes: null,
            created_at: new Date().toISOString(),
            is_key: false,
            execution_result: { status: "matched_intent", executionScore: 90, executionScoreBand: "On target", executionScoreSummary: "Controlled easy run.", whyItMatters: "Recovery between key sessions.", recommendedNextAction: "Keep easy." }
          },
          {
            id: "77777777-7777-4777-8777-777777777793",
            user_id: PREVIEW_USER_ID,
            athlete_id: PREVIEW_USER_ID,
            plan_id: PREVIEW_PLAN_ID,
            week_id: PREVIEW_WEEK_FIVE_ID,
            date: previewDateOffset(mon, 4),
            sport: "bike",
            discipline: "bike",
            type: "Endurance Ride",
            session_name: "Endurance Ride",
            target: "90 min aerobic with cadence drills",
            duration_minutes: 90,
            intent_category: "easy",
            session_role: "supporting",
            status: "planned",
            day_order: 1,
            notes: null,
            created_at: new Date().toISOString(),
            is_key: false,
            execution_result: null
          },
          {
            id: "77777777-7777-4777-8777-777777777794",
            user_id: PREVIEW_USER_ID,
            athlete_id: PREVIEW_USER_ID,
            plan_id: PREVIEW_PLAN_ID,
            week_id: PREVIEW_WEEK_FIVE_ID,
            date: previewDateOffset(mon, 5),
            sport: "run",
            discipline: "run",
            type: "Tempo Run",
            session_name: "Tempo Run",
            target: "50 min with 3 x 10 min @ threshold",
            duration_minutes: 50,
            intent_category: "threshold",
            session_role: "key",
            status: "planned",
            day_order: 1,
            notes: null,
            created_at: new Date().toISOString(),
            is_key: true,
            execution_result: null
          },
          // Sunday of LAST week — completed Olympic-distance race.
          // Surfaces the v2 race review feature: planned race session
          // links to a 5-segment bundle via
          // session_activity_links.match_method = 'race_bundle'. Anchored
          // to the prior week so the current week can host the upcoming
          // Galway 70.3 race.
          {
            id: PREVIEW_RACE_SESSION_ID,
            user_id: PREVIEW_USER_ID,
            athlete_id: PREVIEW_USER_ID,
            plan_id: PREVIEW_PLAN_ID,
            week_id: PREVIEW_WEEK_FIVE_ID,
            date: previewDateOffset(previewPriorRaceMonday(), 6),
            sport: "other",
            discipline: "multi",
            type: "Olympic (race)",
            session_name: "Joe Hannon Olympic",
            target: "Race-pace execution; even splits, controlled bike, hold run pace",
            duration_minutes: Math.round(RACE_TOTAL_DURATION_SEC / 60),
            intent_category: "race",
            session_role: "key",
            status: "completed",
            day_order: 1,
            notes: "B-race rehearsal for Galway 70.3.",
            created_at: new Date().toISOString(),
            is_key: true,
            execution_result: null
          }
        ];
      })()
    ],
  };
}
