// Completed-activity / link / upload seed rows for the preview database.
// Pulled out of data-scenarios.ts so the umbrella file stays scannable.

import {
  PREVIEW_ACTIVITY_EXTRA_RUN_ID,
  PREVIEW_ACTIVITY_LONG_RUN_ID,
  PREVIEW_ACTIVITY_ONE_ID,
  PREVIEW_ACTIVITY_SWIM_ID,
  PREVIEW_ACTIVITY_THREE_ID,
  PREVIEW_ACTIVITY_TWO_ID,
  PREVIEW_ACTIVITY_UNREVIEWED_ID,
  PREVIEW_LINK_EXTRA_RUN_ID,
  PREVIEW_LINK_LONG_RUN_ID,
  PREVIEW_LINK_ONE_ID,
  PREVIEW_LINK_SWIM_ID,
  PREVIEW_LINK_TWO_ID,
  PREVIEW_RACE_ACT_BIKE_ID,
  PREVIEW_RACE_ACT_RUN_ID,
  PREVIEW_RACE_ACT_SWIM_ID,
  PREVIEW_RACE_ACT_T1_ID,
  PREVIEW_RACE_ACT_T2_ID,
  PREVIEW_RACE_BUNDLE_ID,
  PREVIEW_RACE_LINK_BIKE_ID,
  PREVIEW_RACE_LINK_RUN_ID,
  PREVIEW_RACE_LINK_SWIM_ID,
  PREVIEW_RACE_LINK_T1_ID,
  PREVIEW_RACE_LINK_T2_ID,
  PREVIEW_RACE_SESSION_ID,
  PREVIEW_UPLOAD_ID,
  PREVIEW_USER_ID
} from "./data-types";
import {
  RACE_SEGMENT_DURATIONS_SEC,
  previewPriorRaceMonday,
  raceSegmentEndIso,
  raceSegmentStartIso
} from "./data-factories";

export function buildActivityRows() {
  return {
    planned_sessions: [],
    completed_sessions: [
      { id: "88888888-8888-4888-8888-888888888881", user_id: PREVIEW_USER_ID, date: "2026-03-09", sport: "swim" },
      { id: "88888888-8888-4888-8888-888888888882", user_id: PREVIEW_USER_ID, date: "2026-03-10", sport: "bike" },
      { id: "88888888-8888-4888-8888-888888888883", user_id: PREVIEW_USER_ID, date: "2026-03-11", sport: "run" }
    ],
    completed_activities: [
      {
        id: PREVIEW_ACTIVITY_SWIM_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "swim",
        start_time_utc: "2026-03-09T06:30:00.000Z",
        end_time_utc: "2026-03-09T07:18:00.000Z",
        duration_sec: 2880,
        moving_duration_sec: 2880,
        elapsed_duration_sec: 2880,
        distance_m: 1800,
        avg_hr: 132,
        avg_power: null,
        avg_cadence: null,
        max_hr: 148,
        max_power: null,
        elevation_gain_m: null,
        elevation_loss_m: null,
        calories: 480,
        avg_pace_per_100m_sec: 92,
        avg_stroke_rate_spm: 26,
        avg_swolf: 38,
        pool_length_m: 25,
        laps_count: 12,
        activity_vendor: "garmin",
        activity_type_raw: "swimming",
        activity_subtype_raw: "pool_swimming",
        source: "upload",
        parse_summary: null,
        notes: "CSS intervals — 12 x 100m. Pacing held cleanly through the last set.",
        schedule_status: "scheduled",
        is_unplanned: false,
        is_race: false,
        created_at: "2026-03-09T07:20:00.000Z",
        updated_at: "2026-03-09T07:20:00.000Z",
        metrics_v2: {
          paceZones: [
            { zone: 1, durationSec: 300, pctOfSession: 0.10 },
            { zone: 2, durationSec: 900, pctOfSession: 0.31 },
            { zone: 3, durationSec: 1350, pctOfSession: 0.47 },
            { zone: 4, durationSec: 330, pctOfSession: 0.11 }
          ],
          laps: [
            { index: 1, durationSec: 95, distanceM: 100, avgPacePer100mSec: 95 },
            { index: 2, durationSec: 94, distanceM: 100, avgPacePer100mSec: 94 },
            { index: 3, durationSec: 92, distanceM: 100, avgPacePer100mSec: 92 },
            { index: 4, durationSec: 91, distanceM: 100, avgPacePer100mSec: 91 },
            { index: 5, durationSec: 91, distanceM: 100, avgPacePer100mSec: 91 },
            { index: 6, durationSec: 90, distanceM: 100, avgPacePer100mSec: 90 }
          ]
        }
      },
      {
        id: PREVIEW_ACTIVITY_ONE_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "bike",
        start_time_utc: "2026-03-10T06:15:00.000Z",
        end_time_utc: "2026-03-10T07:29:00.000Z",
        duration_sec: 4440,
        moving_duration_sec: 4360,
        elapsed_duration_sec: 4440,
        distance_m: 38200,
        avg_hr: 148,
        avg_power: 212,
        avg_cadence: 88,
        max_hr: 171,
        max_power: 356,
        elevation_gain_m: 420,
        elevation_loss_m: 418,
        calories: 812,
        avg_pace_per_100m_sec: null,
        avg_stroke_rate_spm: null,
        avg_swolf: null,
        pool_length_m: null,
        laps_count: 6,
        activity_vendor: "garmin",
        activity_type_raw: "cycling",
        activity_subtype_raw: "indoor_cycling",
        source: "upload",
        parse_summary: null,
        notes: "Good control through the middle rep.",
        schedule_status: "scheduled",
        is_unplanned: false,
        is_race: false,
        created_at: "2026-03-10T07:40:00.000Z",
        updated_at: "2026-03-10T07:40:00.000Z",
        metrics_v2: {
          power: {
            normalizedPower: 218,
            variabilityIndex: 1.03,
            intensityFactor: 0.88,
            totalWorkKj: 940
          },
          load: {
            trainingStressScore: 83
          },
          cadence: {
            avgCadence: 88,
            maxCadence: 106
          },
          pauses: {
            count: 1,
            totalPausedSec: 34
          },
          environment: {
            avgTemperature: 18.4
          },
          activity: {
            sportProfileName: "Indoor Bike"
          },
          laps: [
            { index: 1, durationSec: 720, distanceM: 11200, avgHr: 146, avgPower: 220, normalizedPower: 224, avgCadence: 89 },
            { index: 2, durationSec: 720, distanceM: 10950, avgHr: 151, avgPower: 217, normalizedPower: 221, avgCadence: 88 }
          ],
          powerZones: [
            { zone: 1, powerMin: null, powerMax: 150, durationSec: 620, pctOfSession: 0.14 },
            { zone: 2, powerMin: 151, powerMax: 210, durationSec: 1180, pctOfSession: 0.27 },
            { zone: 3, powerMin: 211, powerMax: 260, durationSec: 2060, pctOfSession: 0.46 }
          ],
          heartRateZones: [
            { zone: 1, heartRateMin: null, heartRateMax: 130, durationSec: 400, pctOfSession: 0.09 },
            { zone: 2, heartRateMin: 131, heartRateMax: 149, durationSec: 1800, pctOfSession: 0.41 },
            { zone: 3, heartRateMin: 150, heartRateMax: 165, durationSec: 1700, pctOfSession: 0.38 }
          ]
        }
      },
      {
        id: PREVIEW_ACTIVITY_TWO_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "run",
        start_time_utc: "2026-03-11T07:00:00.000Z",
        end_time_utc: "2026-03-11T07:44:00.000Z",
        duration_sec: 2640,
        moving_duration_sec: 2622,
        elapsed_duration_sec: 2640,
        distance_m: 8300,
        avg_hr: 139,
        avg_power: null,
        avg_cadence: 172,
        max_hr: 151,
        max_power: null,
        elevation_gain_m: 48,
        elevation_loss_m: 47,
        calories: 504,
        avg_pace_per_100m_sec: null,
        avg_stroke_rate_spm: null,
        avg_swolf: null,
        pool_length_m: null,
        laps_count: 4,
        activity_vendor: "garmin",
        activity_type_raw: "running",
        activity_subtype_raw: "easy_run",
        source: "upload",
        parse_summary: null,
        notes: null,
        schedule_status: "scheduled",
        is_unplanned: false,
        is_race: false,
        created_at: "2026-03-11T07:48:00.000Z",
        updated_at: "2026-03-11T07:48:00.000Z",
        metrics_v2: {
          cadence: {
            avgCadence: 172
          },
          elevation: {
            gainM: 48
          }
        }
      },
      {
        id: PREVIEW_ACTIVITY_THREE_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "bike",
        start_time_utc: "2026-03-13T18:20:00.000Z",
        end_time_utc: "2026-03-13T18:52:00.000Z",
        duration_sec: 1920,
        moving_duration_sec: 1902,
        elapsed_duration_sec: 1920,
        distance_m: 15100,
        avg_hr: 136,
        avg_power: 186,
        avg_cadence: 87,
        max_hr: 149,
        max_power: 298,
        elevation_gain_m: 98,
        elevation_loss_m: 97,
        calories: 328,
        avg_pace_per_100m_sec: null,
        avg_stroke_rate_spm: null,
        avg_swolf: null,
        pool_length_m: null,
        laps_count: 2,
        activity_vendor: "garmin",
        activity_type_raw: "cycling",
        activity_subtype_raw: "road",
        source: "upload",
        parse_summary: null,
        notes: "Extra spin after work.",
        schedule_status: "unscheduled",
        is_unplanned: true,
        is_race: false,
        created_at: "2026-03-13T18:55:00.000Z",
        updated_at: "2026-03-13T18:55:00.000Z",
        metrics_v2: {
          power: {
            normalizedPower: 191,
            intensityFactor: 0.74
          },
          load: {
            trainingStressScore: 32
          },
          cadence: {
            avgCadence: 87
          }
        }
      },
      {
        id: PREVIEW_ACTIVITY_EXTRA_RUN_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "run",
        start_time_utc: "2026-03-17T06:30:00.000Z",
        end_time_utc: "2026-03-17T07:05:00.000Z",
        duration_sec: 2100,
        moving_duration_sec: 2080,
        elapsed_duration_sec: 2100,
        distance_m: 6200,
        avg_hr: 142,
        avg_power: null,
        avg_cadence: 174,
        max_hr: 156,
        max_power: null,
        elevation_gain_m: 35,
        elevation_loss_m: 34,
        calories: 390,
        avg_pace_per_100m_sec: null,
        avg_stroke_rate_spm: null,
        avg_swolf: null,
        pool_length_m: null,
        laps_count: 3,
        activity_vendor: "garmin",
        activity_type_raw: "running",
        activity_subtype_raw: "easy_run",
        source: "upload",
        parse_summary: null,
        notes: "Squeezed in an extra morning jog.",
        schedule_status: "unscheduled",
        is_unplanned: true,
        is_race: false,
        created_at: "2026-03-17T07:10:00.000Z",
        updated_at: "2026-03-17T07:10:00.000Z",
        metrics_v2: {
          cadence: { avgCadence: 174 },
          elevation: { gainM: 35 }
        }
      },
      {
        id: PREVIEW_ACTIVITY_UNREVIEWED_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "strength",
        start_time_utc: "2026-03-18T12:00:00.000Z",
        end_time_utc: "2026-03-18T12:40:00.000Z",
        duration_sec: 2400,
        moving_duration_sec: 2400,
        elapsed_duration_sec: 2400,
        distance_m: null,
        avg_hr: 118,
        avg_power: null,
        avg_cadence: null,
        max_hr: 138,
        max_power: null,
        elevation_gain_m: null,
        elevation_loss_m: null,
        calories: 220,
        avg_pace_per_100m_sec: null,
        avg_stroke_rate_spm: null,
        avg_swolf: null,
        pool_length_m: null,
        laps_count: null,
        activity_vendor: "garmin",
        activity_type_raw: "strength_training",
        activity_subtype_raw: null,
        source: "upload",
        parse_summary: null,
        notes: null,
        schedule_status: "unscheduled",
        is_unplanned: false,
        is_race: false,
        created_at: "2026-03-18T12:45:00.000Z",
        updated_at: "2026-03-18T12:45:00.000Z",
        metrics_v2: null
      },
      {
        id: PREVIEW_ACTIVITY_LONG_RUN_ID,
        user_id: PREVIEW_USER_ID,
        upload_id: PREVIEW_UPLOAD_ID,
        sport_type: "run",
        start_time_utc: "2026-03-15T07:00:00.000Z",
        end_time_utc: "2026-03-15T08:38:00.000Z",
        duration_sec: 5880,
        moving_duration_sec: 5840,
        elapsed_duration_sec: 5880,
        distance_m: 21000,
        avg_hr: 144,
        avg_power: null,
        avg_cadence: 170,
        max_hr: 162,
        max_power: null,
        elevation_gain_m: 186,
        elevation_loss_m: 184,
        calories: 1260,
        avg_pace_per_100m_sec: null,
        avg_stroke_rate_spm: null,
        avg_swolf: null,
        pool_length_m: null,
        laps_count: 7,
        activity_vendor: "garmin",
        activity_type_raw: "running",
        activity_subtype_raw: "long_run",
        source: "upload",
        parse_summary: null,
        notes: "Solid. Kept it honest for 18km then let the last 3km drift to steady.",
        schedule_status: "scheduled",
        is_unplanned: false,
        is_race: false,
        created_at: "2026-03-15T08:45:00.000Z",
        updated_at: "2026-03-15T09:00:00.000Z",
        metrics_v2: {
          cadence: { avgCadence: 170, maxCadence: 184 },
          elevation: { gainM: 186 },
          heartRateZones: [
            { zone: 1, heartRateMin: null, heartRateMax: 130, durationSec: 480, pctOfSession: 0.08 },
            { zone: 2, heartRateMin: 131, heartRateMax: 149, durationSec: 3720, pctOfSession: 0.64 },
            { zone: 3, heartRateMin: 150, heartRateMax: 165, durationSec: 1560, pctOfSession: 0.27 }
          ],
          laps: [
            { index: 1, durationSec: 840, distanceM: 3000, avgHr: 138, avgPaceSecPerKm: 280 },
            { index: 2, durationSec: 840, distanceM: 3000, avgHr: 141, avgPaceSecPerKm: 280 },
            { index: 3, durationSec: 845, distanceM: 3000, avgHr: 144, avgPaceSecPerKm: 282 },
            { index: 4, durationSec: 848, distanceM: 3000, avgHr: 146, avgPaceSecPerKm: 283 },
            { index: 5, durationSec: 852, distanceM: 3000, avgHr: 148, avgPaceSecPerKm: 284 },
            { index: 6, durationSec: 848, distanceM: 3000, avgHr: 148, avgPaceSecPerKm: 283 },
            { index: 7, durationSec: 767, distanceM: 3000, avgHr: 155, avgPaceSecPerKm: 256 }
          ]
        }
      },
      // ── Race bundle segments (Sunday of LAST week) ──
      // Five activities carrying race_bundle_id + race_segment_role +
      // race_segment_index. Bike halves are populated so the race-review
      // pipeline has real pacing data to chew on; run laps drive a
      // computed-from-laps halves split. Anchored one week in the past so
      // race-week intelligence can use this race as the carry-forward
      // source for the upcoming race seeded below.
      ...(() => {
        const mon = previewPriorRaceMonday();
        return [
          {
            id: PREVIEW_RACE_ACT_SWIM_ID,
            user_id: PREVIEW_USER_ID,
            upload_id: PREVIEW_UPLOAD_ID,
            sport_type: "swim",
            start_time_utc: raceSegmentStartIso(mon, "swim"),
            end_time_utc: raceSegmentEndIso(mon, "swim"),
            duration_sec: RACE_SEGMENT_DURATIONS_SEC.swim,
            moving_duration_sec: RACE_SEGMENT_DURATIONS_SEC.swim,
            elapsed_duration_sec: RACE_SEGMENT_DURATIONS_SEC.swim,
            distance_m: 1500,
            avg_hr: 152,
            avg_power: null,
            avg_cadence: null,
            max_hr: 168,
            max_power: null,
            elevation_gain_m: null,
            elevation_loss_m: null,
            calories: 280,
            avg_pace_per_100m_sec: 107,
            avg_stroke_rate_spm: 30,
            avg_swolf: null,
            pool_length_m: null,
            laps_count: 4,
            activity_vendor: "garmin",
            activity_type_raw: "open_water_swimming",
            activity_subtype_raw: "open_water",
            source: "upload",
            parse_summary: null,
            notes: null,
            schedule_status: "scheduled",
            is_unplanned: false,
            is_race: true,
            race_bundle_id: PREVIEW_RACE_BUNDLE_ID,
            race_segment_role: "swim",
            race_segment_index: 0,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            metrics_v2: {
              laps: [
                { index: 1, durationSec: 410, distanceM: 400, avgPacePer100mSec: 102 },
                { index: 2, durationSec: 405, distanceM: 400, avgPacePer100mSec: 101 },
                { index: 3, durationSec: 395, distanceM: 400, avgPacePer100mSec: 99 },
                { index: 4, durationSec: 391, distanceM: 300, avgPacePer100mSec: 130 }
              ]
            }
          },
          {
            id: PREVIEW_RACE_ACT_T1_ID,
            user_id: PREVIEW_USER_ID,
            upload_id: PREVIEW_UPLOAD_ID,
            sport_type: "strength",
            start_time_utc: raceSegmentStartIso(mon, "t1"),
            end_time_utc: raceSegmentEndIso(mon, "t1"),
            duration_sec: RACE_SEGMENT_DURATIONS_SEC.t1,
            moving_duration_sec: RACE_SEGMENT_DURATIONS_SEC.t1,
            elapsed_duration_sec: RACE_SEGMENT_DURATIONS_SEC.t1,
            distance_m: 213,
            avg_hr: 148,
            avg_power: null,
            avg_cadence: null,
            max_hr: 162,
            max_power: null,
            elevation_gain_m: null,
            elevation_loss_m: null,
            calories: 12,
            avg_pace_per_100m_sec: null,
            avg_stroke_rate_spm: null,
            avg_swolf: null,
            pool_length_m: null,
            laps_count: 1,
            activity_vendor: "garmin",
            activity_type_raw: "transition",
            activity_subtype_raw: "transition",
            source: "upload",
            parse_summary: null,
            notes: null,
            schedule_status: "scheduled",
            is_unplanned: false,
            is_race: true,
            race_bundle_id: PREVIEW_RACE_BUNDLE_ID,
            race_segment_role: "t1",
            race_segment_index: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            metrics_v2: {}
          },
          {
            id: PREVIEW_RACE_ACT_BIKE_ID,
            user_id: PREVIEW_USER_ID,
            upload_id: PREVIEW_UPLOAD_ID,
            sport_type: "bike",
            start_time_utc: raceSegmentStartIso(mon, "bike"),
            end_time_utc: raceSegmentEndIso(mon, "bike"),
            duration_sec: RACE_SEGMENT_DURATIONS_SEC.bike,
            moving_duration_sec: RACE_SEGMENT_DURATIONS_SEC.bike - 18,
            elapsed_duration_sec: RACE_SEGMENT_DURATIONS_SEC.bike,
            distance_m: 39966,
            avg_hr: 158,
            avg_power: 218,
            avg_cadence: 88,
            max_hr: 174,
            max_power: 412,
            elevation_gain_m: 312,
            elevation_loss_m: 308,
            calories: 920,
            avg_pace_per_100m_sec: null,
            avg_stroke_rate_spm: null,
            avg_swolf: null,
            pool_length_m: null,
            laps_count: 4,
            activity_vendor: "garmin",
            activity_type_raw: "cycling",
            activity_subtype_raw: "road_biking",
            source: "upload",
            parse_summary: null,
            notes: null,
            schedule_status: "scheduled",
            is_unplanned: false,
            is_race: true,
            race_bundle_id: PREVIEW_RACE_BUNDLE_ID,
            race_segment_role: "bike",
            race_segment_index: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            metrics_v2: {
              power: { normalizedPower: 224, intensityFactor: 0.91, totalWorkKj: 1010 },
              halves: { firstHalfAvgPower: 220, lastHalfAvgPower: 216 },
              laps: [
                { index: 1, durationSec: 1150, distanceM: 10000, avgHr: 154, avgPower: 222, normalizedPower: 226, avgCadence: 89 },
                { index: 2, durationSec: 1160, distanceM: 10000, avgHr: 158, avgPower: 220, normalizedPower: 224, avgCadence: 88 },
                { index: 3, durationSec: 1155, distanceM: 10000, avgHr: 160, avgPower: 217, normalizedPower: 222, avgCadence: 87 },
                { index: 4, durationSec: 1154, distanceM: 9966,  avgHr: 162, avgPower: 213, normalizedPower: 220, avgCadence: 87 }
              ]
            }
          },
          {
            id: PREVIEW_RACE_ACT_T2_ID,
            user_id: PREVIEW_USER_ID,
            upload_id: PREVIEW_UPLOAD_ID,
            sport_type: "strength",
            start_time_utc: raceSegmentStartIso(mon, "t2"),
            end_time_utc: raceSegmentEndIso(mon, "t2"),
            duration_sec: RACE_SEGMENT_DURATIONS_SEC.t2,
            moving_duration_sec: RACE_SEGMENT_DURATIONS_SEC.t2,
            elapsed_duration_sec: RACE_SEGMENT_DURATIONS_SEC.t2,
            distance_m: 160,
            avg_hr: 156,
            avg_power: null,
            avg_cadence: null,
            max_hr: 165,
            max_power: null,
            elevation_gain_m: null,
            elevation_loss_m: null,
            calories: 10,
            avg_pace_per_100m_sec: null,
            avg_stroke_rate_spm: null,
            avg_swolf: null,
            pool_length_m: null,
            laps_count: 1,
            activity_vendor: "garmin",
            activity_type_raw: "transition",
            activity_subtype_raw: "transition",
            source: "upload",
            parse_summary: null,
            notes: null,
            schedule_status: "scheduled",
            is_unplanned: false,
            is_race: true,
            race_bundle_id: PREVIEW_RACE_BUNDLE_ID,
            race_segment_role: "t2",
            race_segment_index: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            metrics_v2: {}
          },
          {
            id: PREVIEW_RACE_ACT_RUN_ID,
            user_id: PREVIEW_USER_ID,
            upload_id: PREVIEW_UPLOAD_ID,
            sport_type: "run",
            start_time_utc: raceSegmentStartIso(mon, "run"),
            end_time_utc: raceSegmentEndIso(mon, "run"),
            duration_sec: RACE_SEGMENT_DURATIONS_SEC.run,
            moving_duration_sec: RACE_SEGMENT_DURATIONS_SEC.run - 5,
            elapsed_duration_sec: RACE_SEGMENT_DURATIONS_SEC.run,
            distance_m: 9368,
            avg_hr: 168,
            avg_power: null,
            avg_cadence: 178,
            max_hr: 182,
            max_power: null,
            elevation_gain_m: 64,
            elevation_loss_m: 62,
            calories: 590,
            avg_pace_per_100m_sec: null,
            avg_stroke_rate_spm: null,
            avg_swolf: null,
            pool_length_m: null,
            laps_count: 5,
            activity_vendor: "garmin",
            activity_type_raw: "running",
            activity_subtype_raw: "race",
            source: "upload",
            parse_summary: null,
            notes: null,
            schedule_status: "scheduled",
            is_unplanned: false,
            is_race: true,
            race_bundle_id: PREVIEW_RACE_BUNDLE_ID,
            race_segment_role: "run",
            race_segment_index: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            metrics_v2: {
              cadence: { avgCadence: 178, maxCadence: 184 },
              laps: [
                { index: 1, durationSec: 510, distanceM: 2000, avgHr: 162, avgPaceSecPerKm: 255 },
                { index: 2, durationSec: 520, distanceM: 2000, avgHr: 167, avgPaceSecPerKm: 260 },
                { index: 3, durationSec: 535, distanceM: 2000, avgHr: 170, avgPaceSecPerKm: 268 },
                { index: 4, durationSec: 540, distanceM: 2000, avgHr: 172, avgPaceSecPerKm: 270 },
                { index: 5, durationSec: 536, distanceM: 1368, avgHr: 174, avgPaceSecPerKm: 391 }
              ]
            }
          }
        ];
      })()
    ],
    session_activity_links: [
      {
        id: PREVIEW_LINK_ONE_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: "77777777-7777-4777-8777-777777777772",
        completed_activity_id: PREVIEW_ACTIVITY_ONE_ID,
        confidence: 0.93,
        confirmation_status: "confirmed",
        matched_at: "2026-03-10T07:42:00.000Z",
        match_method: "preview"
      },
      {
        id: PREVIEW_LINK_TWO_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: "77777777-7777-4777-8777-777777777773",
        completed_activity_id: PREVIEW_ACTIVITY_TWO_ID,
        confidence: 0.88,
        confirmation_status: "confirmed",
        matched_at: "2026-03-11T07:49:00.000Z",
        match_method: "preview"
      },
      {
        id: PREVIEW_LINK_EXTRA_RUN_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: null,
        completed_activity_id: PREVIEW_ACTIVITY_EXTRA_RUN_ID,
        confidence: null,
        confirmation_status: "rejected",
        matched_at: "2026-03-17T07:12:00.000Z",
        match_method: "unmatched"
      },
      {
        id: PREVIEW_LINK_SWIM_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: "77777777-7777-4777-8777-777777777771",
        completed_activity_id: PREVIEW_ACTIVITY_SWIM_ID,
        confidence: 0.97,
        confirmation_status: "confirmed",
        matched_at: "2026-03-09T07:22:00.000Z",
        match_method: "preview"
      },
      {
        id: PREVIEW_LINK_LONG_RUN_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: "77777777-7777-4777-8777-777777777777",
        completed_activity_id: PREVIEW_ACTIVITY_LONG_RUN_ID,
        confidence: 0.94,
        confirmation_status: "confirmed",
        matched_at: "2026-03-15T09:02:00.000Z",
        match_method: "preview"
      },
      // Race-bundle links: one per segment, all confirmed, all carrying
      // match_method = "race_bundle" so the page-level race detection picks
      // up the segment list and triggers the race-review fetch.
      {
        id: PREVIEW_RACE_LINK_SWIM_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: PREVIEW_RACE_SESSION_ID,
        completed_activity_id: PREVIEW_RACE_ACT_SWIM_ID,
        confidence: 1,
        confirmation_status: "confirmed",
        matched_at: new Date().toISOString(),
        match_method: "race_bundle",
        match_reason: { kind: "race_bundle", role: "swim", segmentIndex: 0, source: "strava_reconstructed" }
      },
      {
        id: PREVIEW_RACE_LINK_T1_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: PREVIEW_RACE_SESSION_ID,
        completed_activity_id: PREVIEW_RACE_ACT_T1_ID,
        confidence: 1,
        confirmation_status: "confirmed",
        matched_at: new Date().toISOString(),
        match_method: "race_bundle",
        match_reason: { kind: "race_bundle", role: "t1", segmentIndex: 1, source: "strava_reconstructed" }
      },
      {
        id: PREVIEW_RACE_LINK_BIKE_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: PREVIEW_RACE_SESSION_ID,
        completed_activity_id: PREVIEW_RACE_ACT_BIKE_ID,
        confidence: 1,
        confirmation_status: "confirmed",
        matched_at: new Date().toISOString(),
        match_method: "race_bundle",
        match_reason: { kind: "race_bundle", role: "bike", segmentIndex: 2, source: "strava_reconstructed" }
      },
      {
        id: PREVIEW_RACE_LINK_T2_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: PREVIEW_RACE_SESSION_ID,
        completed_activity_id: PREVIEW_RACE_ACT_T2_ID,
        confidence: 1,
        confirmation_status: "confirmed",
        matched_at: new Date().toISOString(),
        match_method: "race_bundle",
        match_reason: { kind: "race_bundle", role: "t2", segmentIndex: 3, source: "strava_reconstructed" }
      },
      {
        id: PREVIEW_RACE_LINK_RUN_ID,
        user_id: PREVIEW_USER_ID,
        planned_session_id: PREVIEW_RACE_SESSION_ID,
        completed_activity_id: PREVIEW_RACE_ACT_RUN_ID,
        confidence: 1,
        confirmation_status: "confirmed",
        matched_at: new Date().toISOString(),
        match_method: "race_bundle",
        match_reason: { kind: "race_bundle", role: "run", segmentIndex: 4, source: "strava_reconstructed" }
      }
    ],
    activity_uploads: [
      {
        id: PREVIEW_UPLOAD_ID,
        user_id: PREVIEW_USER_ID,
        filename: "garmin-week-1.fit",
        file_type: "fit",
        created_at: "2026-03-13T19:00:00.000Z",
        status: "matched",
        error_message: null
      }
    ],
  };
}
