/**
 * Historical training plan for D McG — Half IM 2026.
 *
 * Transcribed from the "Tri Training Programme Overview" spreadsheet screenshot.
 * Dates are ISO (YYYY-MM-DD); week start = Monday. The DATE WE column in the
 * sheet is the Sunday week-ending date; weekStartDate below is that Sunday − 6.
 *
 * Splitting rules applied to composite labels:
 *   - "Swim + X | D"     → swim=60, X=D-60 (D includes swim)
 *   - "Gym + X | D"      → gym=45 separate, X=D (coach excluded gym from total)
 *   - "Gym + Swim | D"   → gym=45, swim=60 (both canonical, D ignored)
 *   - "GYM + EZ Spin + OW Swim | D" → gym=45, OW swim=45, spin=D-45
 *   - "Long Brick (X x Y)" → bike + run pair (bike ≈ 2/3 of D, run = remainder)
 *
 * Reconstructed weeks (Blocks 1 & 2, pre 2026-02-23) are marked
 * `reconstructed: true` so you can trace them in source_metadata.
 */

import type { SeedPlan } from "./types";

export const PLAN_2026: SeedPlan = {
  seasonName: "2026 Half Ironman",
  raceName: "Half IM",
  raceDate: "2026-06-07",
  planName: "Ironman Warsaw 70.3 2026",
  planStartDate: "2025-11-03",
  durationWeeks: 31,
  blocks: [
    // ======================================================================
    // BLOCK 1 — PHASE 1: Strength + Bike power (weeks 1–8)
    // Reconstructed retrospectively; planning began ~2026-02-23.
    // ======================================================================
    {
      name: "Block 1 — Strength + Bike Power",
      blockType: "Base",
      startDate: "2025-11-03",
      endDate: "2025-12-28",
      emphasis: ["strength", "bike-power"],
      weeks: [
        {
          weekIndex: 1,
          weekStartDate: "2025-11-03",
          focus: "Build",
          sessions: [
            { date: "2025-11-03", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-11-03", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2025-11-04", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-11-04", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2025-11-06", sport: "bike", sessionName: "FTP", durationMinutes: 30 },
            { date: "2025-11-07", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-11-08", sport: "bike", sessionName: "Long Bike", durationMinutes: 60 },
            { date: "2025-11-09", sport: "run", sessionName: "Long Run", durationMinutes: 60 },
          ],
        },
        {
          weekIndex: 2,
          weekStartDate: "2025-11-10",
          focus: "Build",
          sessions: [
            { date: "2025-11-10", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-11-10", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2025-11-11", sport: "bike", sessionName: "EZ Bike", durationMinutes: 90 },
            { date: "2025-11-13", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2025-11-14", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-11-15", sport: "bike", sessionName: "Long Bike", durationMinutes: 60 },
            { date: "2025-11-16", sport: "run", sessionName: "Long Run", durationMinutes: 60 },
          ],
        },
        {
          weekIndex: 3,
          weekStartDate: "2025-11-17",
          focus: "Build",
          sessions: [
            { date: "2025-11-17", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-11-17", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2025-11-18", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45 },
            { date: "2025-11-20", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2025-11-21", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-11-22", sport: "bike", sessionName: "Long Bike", durationMinutes: 75 },
            { date: "2025-11-23", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 4,
          weekStartDate: "2025-11-24",
          focus: "Build",
          sessions: [
            { date: "2025-11-24", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-11-24", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2025-11-25", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45 },
            { date: "2025-11-27", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2025-11-28", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-11-29", sport: "bike", sessionName: "Long Bike", durationMinutes: 75 },
            { date: "2025-11-30", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 5,
          weekStartDate: "2025-12-01",
          focus: "Build",
          sessions: [
            { date: "2025-12-01", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-12-01", sport: "run", sessionName: "EZ Run", durationMinutes: 45, notes: "EZ Run" },
            { date: "2025-12-02", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45 },
            { date: "2025-12-04", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2025-12-05", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-12-06", sport: "bike", sessionName: "Long Bike", durationMinutes: 90 },
            { date: "2025-12-07", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 6,
          weekStartDate: "2025-12-08",
          focus: "Build",
          sessions: [
            { date: "2025-12-08", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-12-08", sport: "run", sessionName: "EZ Run", durationMinutes: 45, notes: "EZ Run" },
            { date: "2025-12-09", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45 },
            { date: "2025-12-11", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2025-12-12", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-12-13", sport: "bike", sessionName: "Long Bike", durationMinutes: 90 },
            { date: "2025-12-14", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 7,
          weekStartDate: "2025-12-15",
          focus: "Build",
          sessions: [
            { date: "2025-12-15", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2025-12-15", sport: "run", sessionName: "EZ Run", durationMinutes: 45, notes: "EZ Run" },
            { date: "2025-12-16", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45 },
            { date: "2025-12-18", sport: "bike", sessionName: "FTP", durationMinutes: 30 },
            { date: "2025-12-19", sport: "strength", sessionName: "Gym", durationMinutes: 40 },
            { date: "2025-12-20", sport: "bike", sessionName: "Long Bike", durationMinutes: 60 },
            { date: "2025-12-21", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 8,
          weekStartDate: "2025-12-22",
          focus: "Recovery",
          notes: "Rest / sick week — Christmas holiday. Only Friday gym.",
          sessions: [
            { date: "2025-12-26", sport: "strength", sessionName: "Gym", durationMinutes: 50 },
          ],
        },
      ],
    },

    // ======================================================================
    // BLOCK 2 — PHASE 2: Base + Swim (weeks 9–16)
    // Still pre 2026-02-23 — reconstructed.
    // ======================================================================
    {
      name: "Block 2 — Base + Swim",
      blockType: "Base",
      startDate: "2025-12-29",
      endDate: "2026-02-22",
      emphasis: ["base-endurance", "swim-volume"],
      weeks: [
        {
          weekIndex: 9,
          weekStartDate: "2025-12-29",
          focus: "Recovery",
          notes: "Rest / sick week — New Year.",
          sessions: [],
        },
        {
          weekIndex: 10,
          weekStartDate: "2026-01-05",
          focus: "Build",
          sessions: [
            { date: "2026-01-05", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-05", sport: "run", sessionName: "EZ Run", durationMinutes: 70, notes: "EZ Run" },
            { date: "2026-01-06", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-01-06", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-01-07", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2026-01-08", sport: "swim", sessionName: "Swim TT", durationMinutes: 60 },
            { date: "2026-01-09", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-09", sport: "bike", sessionName: "EZ Bike", durationMinutes: 85, notes: "EZ Bike" },
            { date: "2026-01-10", sport: "bike", sessionName: "Long Bike", durationMinutes: 90 },
            { date: "2026-01-11", sport: "run", sessionName: "Long Run", durationMinutes: 60 },
          ],
        },
        {
          weekIndex: 11,
          weekStartDate: "2026-01-12",
          focus: "Build",
          sessions: [
            { date: "2026-01-12", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-12", sport: "run", sessionName: "EZ Run", durationMinutes: 70, notes: "EZ Run" },
            { date: "2026-01-13", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-01-13", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-01-14", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2026-01-15", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-01-15", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-01-16", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-16", sport: "bike", sessionName: "EZ Bike", durationMinutes: 85, notes: "EZ Bike" },
            { date: "2026-01-17", sport: "bike", sessionName: "Long Bike", durationMinutes: 105 },
            { date: "2026-01-18", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 12,
          weekStartDate: "2026-01-19",
          focus: "Build",
          sessions: [
            { date: "2026-01-19", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-19", sport: "run", sessionName: "EZ Run", durationMinutes: 85, notes: "EZ Run" },
            { date: "2026-01-20", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-01-20", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-01-21", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2026-01-22", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-01-22", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-01-23", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-23", sport: "bike", sessionName: "EZ Bike", durationMinutes: 85, notes: "EZ Bike" },
            { date: "2026-01-24", sport: "bike", sessionName: "Long Bike (3 x 10)", durationMinutes: 105, target: "3 x 10" },
            { date: "2026-01-25", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 13,
          weekStartDate: "2026-01-26",
          focus: "Recovery",
          notes: "Sick week — most sessions missed.",
          sessions: [
            { date: "2026-01-26", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-01-26", sport: "run", sessionName: "EZ Run", durationMinutes: 85, notes: "EZ Run" },
            { date: "2026-01-27", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-01-27", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-01-28", sport: "bike", sessionName: "Power Bike", durationMinutes: 30, notes: "Sick — reduced" },
            { date: "2026-01-31", sport: "bike", sessionName: "Long Bike (3 x 10)", durationMinutes: 120, target: "3 x 10" },
            { date: "2026-02-01", sport: "run", sessionName: "Long Run", durationMinutes: 75 },
          ],
        },
        {
          weekIndex: 14,
          weekStartDate: "2026-02-02",
          focus: "Build",
          sessions: [
            { date: "2026-02-02", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-02-02", sport: "run", sessionName: "EZ Run", durationMinutes: 85, notes: "EZ Run" },
            { date: "2026-02-03", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-02-03", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-02-04", sport: "bike", sessionName: "FTP", durationMinutes: 60 },
            { date: "2026-02-05", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-02-05", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-02-06", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-02-06", sport: "bike", sessionName: "EZ Bike", durationMinutes: 85, notes: "EZ Bike" },
            { date: "2026-02-07", sport: "bike", sessionName: "Long Bike (3 x 15)", durationMinutes: 120, target: "3 x 15" },
            { date: "2026-02-08", sport: "run", sessionName: "Long Run", durationMinutes: 90 },
          ],
        },
        {
          weekIndex: 15,
          weekStartDate: "2026-02-09",
          focus: "Recovery",
          notes: "Ski trip Thu–Sun — rest days, no training.",
          sessions: [
            { date: "2026-02-09", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-02-09", sport: "run", sessionName: "EZ Run", durationMinutes: 100, notes: "EZ Run" },
            { date: "2026-02-10", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-02-10", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-02-11", sport: "bike", sessionName: "EZ Bike", durationMinutes: 60 },
          ],
        },
        {
          weekIndex: 16,
          weekStartDate: "2026-02-16",
          focus: "Build",
          notes: "Returning from ski trip — Mon & Tue rest, training resumes Wed.",
          sessions: [
            { date: "2026-02-18", sport: "bike", sessionName: "Power Bike (60/60)", durationMinutes: 60, target: "60/60" },
            { date: "2026-02-19", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-02-19", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-02-20", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-02-20", sport: "bike", sessionName: "EZ Bike", durationMinutes: 85, notes: "EZ Bike" },
            { date: "2026-02-21", sport: "bike", sessionName: "Long Bike (3 x 15)", durationMinutes: 135, target: "3 x 15" },
            { date: "2026-02-22", sport: "run", sessionName: "Long Run (3 x 5)", durationMinutes: 90, target: "3 x 5" },
          ],
        },
      ],
    },

    // ======================================================================
    // BLOCK 3 — PHASE 3: Build (weeks 17–24)
    // From 2026-02-23 — planned prospectively.
    // ======================================================================
    {
      name: "Block 3 — Build",
      blockType: "Build",
      startDate: "2026-02-23",
      endDate: "2026-04-19",
      emphasis: ["bike-intervals", "swim-run-brick", "long-ride"],
      weeks: [
        {
          weekIndex: 17,
          weekStartDate: "2026-02-23",
          focus: "Build",
          sessions: [
            { date: "2026-02-23", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-02-23", sport: "run", sessionName: "EZ Run", durationMinutes: 70, notes: "EZ Run" },
            { date: "2026-02-24", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-02-24", sport: "run", sessionName: "EZ Run", durationMinutes: 45, notes: "EZ Run" },
            { date: "2026-02-25", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2026-02-26", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-02-26", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-02-28", sport: "bike", sessionName: "Long Bike (5 x 20s sprints)", durationMinutes: 90, target: "5 x 20s sprints" },
            { date: "2026-03-01", sport: "run", sessionName: "Lusk 4 Miler (race)", durationMinutes: 60, notes: "Race" },
          ],
        },
        {
          weekIndex: 18,
          weekStartDate: "2026-03-02",
          focus: "Build",
          sessions: [
            { date: "2026-03-02", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-02", sport: "run", sessionName: "EZ Run", durationMinutes: 70, notes: "EZ Run" },
            { date: "2026-03-03", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-03", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-03-04", sport: "bike", sessionName: "Power Bike (60/60)", durationMinutes: 60, target: "60/60" },
            { date: "2026-03-05", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-05", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-03-06", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-06", sport: "bike", sessionName: "EZ Spin", durationMinutes: 100, notes: "EZ Spin" },
            { date: "2026-03-07", sport: "bike", sessionName: "Long Bike (3 x 20)", durationMinutes: 150, target: "3 x 20" },
            { date: "2026-03-08", sport: "run", sessionName: "Long Run (3 x 10)", durationMinutes: 75, target: "3 x 10" },
          ],
        },
        {
          weekIndex: 19,
          weekStartDate: "2026-03-09",
          focus: "Build",
          sessions: [
            { date: "2026-03-09", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-09", sport: "run", sessionName: "EZ Run", durationMinutes: 70, notes: "EZ Run" },
            { date: "2026-03-10", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-10", sport: "run", sessionName: "Run (5 x 1/1)", durationMinutes: 45, target: "5 x 1/1", notes: "Run (5 x 1/1)" },
            { date: "2026-03-11", sport: "bike", sessionName: "Power Bike (90/90)", durationMinutes: 60, target: "90/90" },
            { date: "2026-03-12", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-12", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-03-13", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-13", sport: "bike", sessionName: "EZ Spin", durationMinutes: 105, notes: "EZ Spin" },
            { date: "2026-03-14", sport: "bike", sessionName: "Long Bike (3 x 20)", durationMinutes: 150, target: "3 x 20" },
            { date: "2026-03-15", sport: "run", sessionName: "Long Run (3 x 10)", durationMinutes: 75, target: "3 x 10" },
          ],
        },
        {
          weekIndex: 20,
          weekStartDate: "2026-03-16",
          focus: "Build",
          sessions: [
            { date: "2026-03-16", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-16", sport: "run", sessionName: "EZ Run", durationMinutes: 85, notes: "EZ Run" },
            { date: "2026-03-17", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-17", sport: "run", sessionName: "Run (5 x 90/90)", durationMinutes: 45, target: "5 x 90/90", notes: "Run (5 x 90/90)" },
            { date: "2026-03-18", sport: "bike", sessionName: "Power Bike (2/2)", durationMinutes: 60, target: "2/2" },
            { date: "2026-03-19", sport: "swim", sessionName: "Swim TT - 1,500", durationMinutes: 60, target: "1,500m TT" },
            { date: "2026-03-20", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-20", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-03-20", sport: "bike", sessionName: "EZ Spin", durationMinutes: 65, notes: "EZ Spin" },
            { date: "2026-03-21", sport: "bike", sessionName: "Long Bike (3 x 20)", durationMinutes: 165, target: "3 x 20" },
            { date: "2026-03-22", sport: "run", sessionName: "Long Run (3 x 15)", durationMinutes: 75, target: "3 x 15" },
          ],
        },
        {
          weekIndex: 21,
          weekStartDate: "2026-03-23",
          focus: "Build",
          sessions: [
            { date: "2026-03-23", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-23", sport: "run", sessionName: "EZ Run", durationMinutes: 85, notes: "EZ Run" },
            { date: "2026-03-24", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-24", sport: "run", sessionName: "Run (5 x 2/2)", durationMinutes: 45, target: "5 x 2/2", notes: "Run (5 x 2/2)" },
            { date: "2026-03-25", sport: "bike", sessionName: "FTP", durationMinutes: 30 },
            { date: "2026-03-26", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-26", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-03-27", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-27", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-03-27", sport: "bike", sessionName: "EZ Spin", durationMinutes: 70, notes: "EZ Spin" },
            { date: "2026-03-28", sport: "bike", sessionName: "Long Bike (3 x 20)", durationMinutes: 165, target: "3 x 20" },
            { date: "2026-03-29", sport: "run", sessionName: "Long Run (3 x 15)", durationMinutes: 75, target: "3 x 15" },
          ],
        },
        {
          weekIndex: 22,
          weekStartDate: "2026-03-30",
          focus: "Build",
          sessions: [
            { date: "2026-03-30", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-03-30", sport: "run", sessionName: "EZ Run", durationMinutes: 85, notes: "EZ Run" },
            { date: "2026-03-31", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-03-31", sport: "run", sessionName: "Run (5 x 3/2)", durationMinutes: 45, target: "5 x 3/2", notes: "Run (5 x 3/2)" },
            { date: "2026-04-01", sport: "bike", sessionName: "Power Bike (SS 2 x 5)", durationMinutes: 60, target: "SS 2 x 5" },
            { date: "2026-04-02", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-04-02", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-04-03", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-04-03", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-04-03", sport: "bike", sessionName: "EZ Spin", durationMinutes: 75, notes: "EZ Spin" },
            { date: "2026-04-04", sport: "bike", sessionName: "Long Bike (3 x 20)", durationMinutes: 180, target: "3 x 20" },
            { date: "2026-04-05", sport: "run", sessionName: "Long Run (3 x 20)", durationMinutes: 90, target: "3 x 20" },
          ],
        },
        {
          weekIndex: 23,
          weekStartDate: "2026-04-06",
          focus: "Build",
          sessions: [
            { date: "2026-04-06", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-04-06", sport: "run", sessionName: "EZ Run", durationMinutes: 100, notes: "EZ Run" },
            { date: "2026-04-07", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-04-07", sport: "run", sessionName: "Run (5 x 4/2)", durationMinutes: 45, target: "5 x 4/2", notes: "Run (5 x 4/2)" },
            { date: "2026-04-08", sport: "bike", sessionName: "Power Bike (SS 2 x 10)", durationMinutes: 60, target: "SS 2 x 10" },
            { date: "2026-04-09", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-04-09", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-04-10", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-04-10", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-04-10", sport: "bike", sessionName: "EZ Spin", durationMinutes: 80, notes: "EZ Spin" },
            { date: "2026-04-11", sport: "bike", sessionName: "Long Bike (3 x 30)", durationMinutes: 180, target: "3 x 30" },
            { date: "2026-04-12", sport: "run", sessionName: "Long Run (3 x 20)", durationMinutes: 90, target: "3 x 20" },
          ],
        },
        {
          weekIndex: 24,
          weekStartDate: "2026-04-13",
          focus: "Build",
          sessions: [
            { date: "2026-04-13", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-04-13", sport: "bike", sessionName: "Long Bike", durationMinutes: 100, notes: "Long Bike" },
            { date: "2026-04-14", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-04-14", sport: "run", sessionName: "Run (5 x 5/2)", durationMinutes: 45, target: "5 x 5/2", notes: "Run (5 x 5/2)" },
            { date: "2026-04-15", sport: "bike", sessionName: "Power Bike (SS 2 x 15)", durationMinutes: 60, target: "SS 2 x 15" },
            { date: "2026-04-16", sport: "swim", sessionName: "Swim TT - 1,500", durationMinutes: 60, target: "1,500m TT" },
            { date: "2026-04-17", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-04-17", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-04-17", sport: "bike", sessionName: "EZ Spin", durationMinutes: 80, notes: "EZ Spin" },
            { date: "2026-04-18", sport: "bike", sessionName: "Long Bike (3 x 30)", durationMinutes: 180, target: "3 x 30" },
            { date: "2026-04-19", sport: "run", sessionName: "Long Run (2 x 30)", durationMinutes: 90, target: "2 x 30" },
          ],
        },
      ],
    },

    // ======================================================================
    // BLOCK 4 — PHASE 4: Race Ready (weeks 25–31, includes taper + race)
    // ======================================================================
    {
      name: "Block 4 — Race Ready",
      blockType: "Peak",
      startDate: "2026-04-20",
      endDate: "2026-06-07",
      emphasis: ["brick-volume", "open-water", "race-simulation", "taper"],
      weeks: [
        {
          weekIndex: 25,
          weekStartDate: "2026-04-20",
          focus: "Race",
          notes: "Joe Hannon Olympic race on Sunday — reduced volume race week.",
          sessions: [
            { date: "2026-04-20", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-04-20", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-04-22", sport: "bike", sessionName: "FTP", durationMinutes: 30 },
            { date: "2026-04-23", sport: "swim", sessionName: "Swim", durationMinutes: 60 },
            { date: "2026-04-25", sport: "run", sessionName: "Run + Strides", durationMinutes: 20, notes: "Pre-race activation" },
            { date: "2026-04-26", sport: "other", sessionName: "Joe Hannon Olympic (race)", durationMinutes: 150, notes: "Olympic-distance triathlon race — 1.5km / 40km / 10km" },
          ],
        },
        {
          weekIndex: 26,
          weekStartDate: "2026-04-27",
          focus: "Build",
          notes: "Recovery Mon, then full race-ready build.",
          sessions: [
            { date: "2026-04-28", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-04-28", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45, notes: "EZ Bike" },
            { date: "2026-04-29", sport: "bike", sessionName: "EZ Bike", durationMinutes: 60 },
            { date: "2026-04-30", sport: "swim", sessionName: "Swim", durationMinutes: 40 },
            { date: "2026-05-01", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-05-01", sport: "bike", sessionName: "EZ Spin", durationMinutes: 40, notes: "EZ Spin" },
            { date: "2026-05-02", sport: "bike", sessionName: "Long Bike (3 x 45)", durationMinutes: 210, target: "3 x 45" },
            { date: "2026-05-03", sport: "run", sessionName: "Long Run (3 x 20)", durationMinutes: 75, target: "3 x 20" },
          ],
        },
        {
          weekIndex: 27,
          weekStartDate: "2026-05-04",
          focus: "Build",
          sessions: [
            { date: "2026-05-04", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-05-04", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-05-05", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-05-05", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45, notes: "EZ Bike" },
            { date: "2026-05-06", sport: "bike", sessionName: "EZ Bike", durationMinutes: 60 },
            { date: "2026-05-07", sport: "swim", sessionName: "Swim TT", durationMinutes: 60 },
            { date: "2026-05-08", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-05-08", sport: "bike", sessionName: "EZ Spin", durationMinutes: 40, notes: "EZ Spin" },
            { date: "2026-05-09", sport: "bike", sessionName: "Long Brick bike (3 x 60)", durationMinutes: 180, target: "3 x 60", notes: "Long Brick bike leg" },
            { date: "2026-05-09", sport: "run", sessionName: "Long Brick run", durationMinutes: 30, notes: "Brick run off the bike" },
            { date: "2026-05-10", sport: "run", sessionName: "Long Run (3 x 20)", durationMinutes: 75, target: "3 x 20" },
          ],
        },
        {
          weekIndex: 28,
          weekStartDate: "2026-05-11",
          focus: "Build",
          sessions: [
            { date: "2026-05-11", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-05-11", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-05-12", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-05-12", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45, notes: "EZ Bike" },
            { date: "2026-05-13", sport: "bike", sessionName: "EZ Bike", durationMinutes: 60 },
            { date: "2026-05-14", sport: "bike", sessionName: "Power Bike", durationMinutes: 90 },
            { date: "2026-05-15", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-05-15", sport: "bike", sessionName: "EZ Spin", durationMinutes: 40, notes: "EZ Spin" },
            { date: "2026-05-16", sport: "bike", sessionName: "Long Brick bike (2 x 90)", durationMinutes: 180, target: "2 x 90", notes: "Long Brick bike leg" },
            { date: "2026-05-16", sport: "run", sessionName: "Long Brick run", durationMinutes: 30, notes: "Brick run off the bike" },
            { date: "2026-05-17", sport: "run", sessionName: "Long Run (2 x 30)", durationMinutes: 90, target: "2 x 30" },
          ],
        },
        {
          weekIndex: 29,
          weekStartDate: "2026-05-18",
          focus: "Build",
          notes: "Peak week — longest brick and biggest volume.",
          sessions: [
            { date: "2026-05-18", sport: "strength", sessionName: "Gym", durationMinutes: 45, notes: "Gym" },
            { date: "2026-05-18", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-05-19", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-05-19", sport: "bike", sessionName: "EZ Bike", durationMinutes: 45, notes: "EZ Bike" },
            { date: "2026-05-20", sport: "bike", sessionName: "EZ Bike", durationMinutes: 60 },
            { date: "2026-05-21", sport: "bike", sessionName: "Power Bike", durationMinutes: 90 },
            { date: "2026-05-22", sport: "swim", sessionName: "Swim", durationMinutes: 45, notes: "Swim" },
            { date: "2026-05-22", sport: "run", sessionName: "EZ Run", durationMinutes: 40, notes: "EZ Run" },
            { date: "2026-05-23", sport: "bike", sessionName: "Long Brick bike (1 x 180)", durationMinutes: 180, target: "1 x 180", notes: "Long Brick bike leg" },
            { date: "2026-05-23", sport: "run", sessionName: "Long Brick run", durationMinutes: 30, notes: "Brick run off the bike" },
            { date: "2026-05-24", sport: "run", sessionName: "Long Run (2 x 30)", durationMinutes: 90, target: "2 x 30" },
          ],
        },
        {
          weekIndex: 30,
          weekStartDate: "2026-05-25",
          focus: "Taper",
          notes: "First taper week.",
          sessions: [
            { date: "2026-05-26", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-05-26", sport: "bike", sessionName: "EZ Bike", durationMinutes: 30, notes: "EZ Bike" },
            { date: "2026-05-27", sport: "bike", sessionName: "Power Bike", durationMinutes: 60 },
            { date: "2026-05-28", sport: "swim", sessionName: "Swim", durationMinutes: 60, notes: "Swim" },
            { date: "2026-05-28", sport: "run", sessionName: "EZ Run", durationMinutes: 30, notes: "EZ Run" },
            { date: "2026-05-29", sport: "swim", sessionName: "OW Swim", durationMinutes: 45, notes: "OW Swim" },
            { date: "2026-05-29", sport: "bike", sessionName: "EZ Spin", durationMinutes: 40, notes: "EZ Spin" },
            { date: "2026-05-30", sport: "bike", sessionName: "Long Brick bike", durationMinutes: 120, notes: "Long Brick bike leg" },
            { date: "2026-05-30", sport: "run", sessionName: "Long Brick run", durationMinutes: 30, notes: "Brick run off the bike" },
            { date: "2026-05-31", sport: "run", sessionName: "Long Run", durationMinutes: 60 },
          ],
        },
        {
          weekIndex: 31,
          weekStartDate: "2026-06-01",
          focus: "Race",
          notes: "Race week — Half IM Sunday 7 June 2026.",
          sessions: [
            { date: "2026-06-01", sport: "run", sessionName: "EZ Run", durationMinutes: 30 },
            { date: "2026-06-03", sport: "bike", sessionName: "FTP Test", durationMinutes: 30, target: "FTP test" },
            { date: "2026-06-04", sport: "swim", sessionName: "Swim", durationMinutes: 60 },
            { date: "2026-06-06", sport: "run", sessionName: "Run + Strides", durationMinutes: 20, notes: "Pre-race activation" },
            { date: "2026-06-07", sport: "other", sessionName: "Half IM (race)", durationMinutes: 330, notes: "Half Ironman race — 1.9km swim / 90km bike / 21.1km run" },
          ],
        },
      ],
    },
  ],
};
