-- Phase 1C: Race review AI Layer 3 — per-segment diagnostic drill-downs.
--
-- Adds two jsonb columns to race_reviews:
--
--   segment_diagnostics — array (or null) of one packet per discipline that
--     has data, carrying the four reference frames (vs Plan, vs Threshold,
--     vs Best Comparable Training, vs Prior Race), the pacing analysis
--     (split type + drift/decoupling observations only when the gates fire),
--     0–3 anomalies, and the AI narrative synthesis.
--
--   transitions_analysis — { t1, t2 } compact comparison of the athlete's
--     transition times against distance-keyed population medians, plus the
--     end-of-leg HR. Null when transitions are inferred (Strava-stitched)
--     since the timestamps are too uncertain for an honest comparison.
--
-- Both are nullable; existing rows generated by the Phase 1A/1B pipeline
-- stay valid until they regenerate and pick up the new fields.
ALTER TABLE public.race_reviews
  ADD COLUMN IF NOT EXISTS segment_diagnostics jsonb,
  ADD COLUMN IF NOT EXISTS transitions_analysis jsonb;
